title: Caro Tracking Some Deadlines
description: Countdowns to some deadlines
author: Carolin Brandt

domain: "aideadlin.es"
baseurl: ""

# twitter_hashtag: machinelearning
github_username: paperswithcode
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
