title: Caro Tracking Some Deadlines
description: Countdowns to some deadlines
author: Carolin Brandt

domain: "carolin-brandt.de"
baseurl: "deadlines"

# twitter_hashtag: machinelearning
github_username: lacinoire
github_repo: deadlines

markdown: kramdown
ga_id:

include: ['_pages']
